
import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/Card';
import { Button } from './ui/Button';

export const MASTER_SQL_SCRIPT = `
-- 1. Enable Vector Extension (Must be first for RAG)
create extension if not exists vector;

-- 2. Create Organizations Table (Stores Plan & Credits)
create table if not exists organizations (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  plan text default 'Free',
  credits int default 30,
  subscription_status text default 'active',
  current_period_end timestamptz,
  stripe_customer_id text,
  created_at timestamptz default now()
);

-- 3. Create Profiles Table (Links User to Organization)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  full_name text,
  organization_id uuid references organizations(id),
  role text default 'owner',
  created_at timestamptz default now()
);

-- 4. Create Messages Table (Chat History for Dashboard)
create table if not exists messages (
  id bigint generated by default as identity primary key,
  text text,
  sender text, -- 'user' or 'bot'
  phone text,
  intent_tag text,
  created_at timestamptz default now()
);

-- 5. Create Early Access Signups Table (Landing Page Leads)
create table if not exists early_access_signups (
  id bigint generated by default as identity primary key,
  full_name text,
  work_email text,
  company_name text,
  industry text,
  team_size text,
  selected_plan text,
  billing_preference text,
  estimated_conversations text,
  created_at timestamptz default now()
);

-- 6. Create Knowledge Table (Vector Store for AI)
create table if not exists knowledge (
  id bigint generated by default as identity primary key,
  organization_id uuid references organizations(id),
  content text,
  metadata jsonb,
  embedding vector(768) -- Gemini Text Embedding 004 Dimension
);

-- 7. Create Vector Search Function (RAG)
create or replace function match_knowledge (
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    knowledge.id,
    knowledge.content,
    1 - (knowledge.embedding <=> query_embedding) as similarity
  from knowledge
  where 1 - (knowledge.embedding <=> query_embedding) > match_threshold
  order by knowledge.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- 8. Enable Row Level Security (Optional for Demo / Required for Prod)
alter table profiles enable row level security;
alter table organizations enable row level security;
alter table messages enable row level security;
alter table knowledge enable row level security;
alter table early_access_signups enable row level security;

-- 9. Create Basic RLS Policies (Permissive for Demo)
create policy "Public profiles access" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Public read organizations" on organizations for select using (true);
create policy "Public insert messages" on messages for insert with check (true);
create policy "Public read messages" on messages for select using (true);
create policy "Public insert signups" on early_access_signups for insert with check (true);
`;

const SupabaseSetup: React.FC = () => {
  return (
    <div className="flex items-center justify-center min-h-screen bg-slate-950 p-4">
      <Card className="w-full max-w-2xl mx-auto border-slate-800 bg-slate-900 text-white">
        <CardHeader>
          <CardTitle className="text-xl md:text-2xl text-white">Database Setup Required</CardTitle>
          <CardDescription className="text-slate-400">
            To support Organizations, Plans, Chat History, and AI credits, please run the following SQL in your Supabase SQL Editor.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="p-4 bg-slate-950 rounded-md border border-slate-800">
            <pre className="text-xs text-blue-300 overflow-x-auto font-mono max-h-[400px]">
              <code>{MASTER_SQL_SCRIPT}</code>
            </pre>
          </div>
          <div className="flex justify-end gap-2">
            <Button 
                variant="outline" 
                onClick={() => navigator.clipboard.writeText(MASTER_SQL_SCRIPT)}
                className="border-slate-700 text-slate-300 hover:bg-slate-800"
            >
                Copy SQL
            </Button>
            <Button onClick={() => window.open('https://supabase.com/dashboard/project/_/sql', '_blank')} className="bg-green-600 hover:bg-green-500 text-white">
                Open Supabase SQL Editor
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default SupabaseSetup;
