
import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/Card';
import { Button } from './ui/Button';

const SupabaseSetup: React.FC = () => {
  const sqlScript = `
-- 1. Create Organizations Table (Stores Plan & Credits)
create table if not exists organizations (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  plan text default 'Free',
  credits int default 30,
  subscription_status text default 'active',
  current_period_end timestamptz,
  stripe_customer_id text,
  created_at timestamptz default now()
);

-- 2. Create Profiles Table (Links User to Organization)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  full_name text,
  organization_id uuid references organizations(id),
  role text default 'owner',
  created_at timestamptz default now()
);

-- 3. Enable RLS (Row Level Security) - Optional for Demo, Recommended for Prod
alter table profiles enable row level security;
alter table organizations enable row level security;

-- 4. Enable Vector Extension (For AI Knowledge Base)
create extension if not exists vector;

-- 5. Create Knowledge Table
create table if not exists knowledge (
  id bigint generated by default as identity primary key,
  organization_id uuid references organizations(id),
  content text,
  metadata jsonb,
  embedding vector(768)
);

-- 6. Create Search Function
create or replace function match_knowledge (
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    knowledge.id,
    knowledge.content,
    1 - (knowledge.embedding <=> query_embedding) as similarity
  from knowledge
  where 1 - (knowledge.embedding <=> query_embedding) > match_threshold
  order by knowledge.embedding <=> query_embedding
  limit match_count;
end;
$$;
`;

  return (
    <div className="flex items-center justify-center min-h-screen bg-slate-950 p-4">
      <Card className="w-full max-w-2xl mx-auto border-slate-800 bg-slate-900 text-white">
        <CardHeader>
          <CardTitle className="text-xl md:text-2xl text-white">Database Setup Required</CardTitle>
          <CardDescription className="text-slate-400">
            To support Organizations, Plans, and AI credits, please run the following SQL in your Supabase SQL Editor.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="p-4 bg-slate-950 rounded-md border border-slate-800">
            <pre className="text-xs text-blue-300 overflow-x-auto font-mono max-h-[400px]">
              <code>{sqlScript}</code>
            </pre>
          </div>
          <div className="flex justify-end gap-2">
            <Button 
                variant="outline" 
                onClick={() => navigator.clipboard.writeText(sqlScript)}
                className="border-slate-700 text-slate-300 hover:bg-slate-800"
            >
                Copy SQL
            </Button>
            <Button onClick={() => window.open('https://supabase.com/dashboard/project/_/sql', '_blank')} className="bg-green-600 hover:bg-green-500 text-white">
                Open Supabase SQL Editor
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default SupabaseSetup;
