
import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/Card';
import { Button } from './ui/Button';

export const MASTER_SQL_SCRIPT = `
-- ==========================================
-- INSHOPPE AI MASTER SETUP SCRIPT (UPDATED)
-- ==========================================

-- 1. Enable Vector Extension (Must be first for RAG)
create extension if not exists vector;

-- 2. Create Organizations Table
create table if not exists organizations (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  plan text default 'Free',
  credits int default 30,
  subscription_status text default 'active',
  current_period_end timestamptz,
  stripe_customer_id text,
  created_at timestamptz default now()
);

-- 3. Create Profiles Table
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  full_name text,
  organization_id uuid references organizations(id),
  role text default 'owner',
  created_at timestamptz default now()
);

-- 4. Create Messages Table
create table if not exists messages (
  id bigint generated by default as identity primary key,
  organization_id uuid references organizations(id),
  text text,
  sender text,
  phone text,
  intent_tag text,
  created_at timestamptz default now()
);

-- SAFETY: Add organization_id column if it does not exist (for existing tables)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'messages' and column_name = 'organization_id') then
    alter table messages add column organization_id uuid references organizations(id);
  end if;
end $$;

-- 5. Create Early Access Signups Table
create table if not exists early_access_signups (
  id bigint generated by default as identity primary key,
  full_name text,
  work_email text,
  company_name text,
  industry text,
  team_size text,
  selected_plan text,
  billing_preference text,
  estimated_conversations text,
  created_at timestamptz default now()
);

-- 6. Create Knowledge Table
create table if not exists knowledge (
  id bigint generated by default as identity primary key,
  organization_id uuid references organizations(id),
  content text,
  metadata jsonb,
  embedding vector(768)
);

-- SAFETY: Add organization_id column to knowledge if missing
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'knowledge' and column_name = 'organization_id') then
    alter table knowledge add column organization_id uuid references organizations(id);
  end if;
end $$;

-- 7. Vector Search Function
create or replace function match_knowledge (
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    knowledge.id,
    knowledge.content,
    1 - (knowledge.embedding <=> query_embedding) as similarity
  from knowledge
  where 1 - (knowledge.embedding <=> query_embedding) > match_threshold
  order by knowledge.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- 8. Enable RLS
alter table profiles enable row level security;
alter table organizations enable row level security;
alter table messages enable row level security;
alter table knowledge enable row level security;
alter table early_access_signups enable row level security;

-- 9. RLS Policies (Drop existing first to allow updates)

-- Profiles
drop policy if exists "Public profiles access" on profiles;
drop policy if exists "Users can insert their own profile" on profiles;
drop policy if exists "Users can update own profile" on profiles;

create policy "Public profiles access" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Organizations
drop policy if exists "Public read organizations" on organizations;
drop policy if exists "Authenticated users can insert orgs" on organizations;
drop policy if exists "Members can update their org" on organizations;

create policy "Public read organizations" on organizations for select using (true);
create policy "Authenticated users can insert orgs" on organizations for insert with check (auth.role() = 'authenticated');
create policy "Members can update their org" on organizations for update using (
  id in (select organization_id from profiles where profiles.id = auth.uid())
);

-- Messages & Knowledge (Secured by Organization)
drop policy if exists "Org members can read messages" on messages;
drop policy if exists "Org members can insert messages" on messages;

create policy "Org members can read messages" on messages for select using (
  organization_id in (select organization_id from profiles where profiles.id = auth.uid())
);
create policy "Org members can insert messages" on messages for insert with check (
  organization_id in (select organization_id from profiles where profiles.id = auth.uid())
);

drop policy if exists "Org members can read knowledge" on knowledge;
drop policy if exists "Org members can insert knowledge" on knowledge;

create policy "Org members can read knowledge" on knowledge for select using (
  organization_id in (select organization_id from profiles where profiles.id = auth.uid())
);
create policy "Org members can insert knowledge" on knowledge for insert with check (
  organization_id in (select organization_id from profiles where profiles.id = auth.uid())
);

-- Signups (Public)
drop policy if exists "Public insert signups" on early_access_signups;
create policy "Public insert signups" on early_access_signups for insert with check (true);

-- 10. AUTOMATIC ONBOARDING TRIGGER
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  new_org_id uuid;
  user_company_name text;
begin
  -- Get company name from metadata or default
  user_company_name := new.raw_user_meta_data->>'company_name';
  if user_company_name is null or user_company_name = '' then
    user_company_name := 'My Workspace';
  end if;

  -- 1. Create Organization
  insert into public.organizations (name, plan, credits, subscription_status)
  values (user_company_name, 'Free', 30, 'active')
  returning id into new_org_id;

  -- 2. Create Profile linked to Org
  insert into public.profiles (id, email, full_name, organization_id, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new_org_id,
    'owner'
  );

  return new;
end;
$$;

-- Drop trigger if exists to allow updates
drop trigger if exists on_auth_user_created on auth.users;

-- Create the trigger
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute procedure public.handle_new_user();
`;

const SupabaseSetup: React.FC = () => {
  return (
    <div className="flex items-center justify-center min-h-screen bg-slate-950 p-4">
      <Card className="w-full max-w-2xl mx-auto border-slate-800 bg-slate-900 text-white">
        <CardHeader>
          <CardTitle className="text-xl md:text-2xl text-white">Database Setup Required</CardTitle>
          <CardDescription className="text-slate-400">
            To support Organizations, Plans, Chat History, and AI credits, please run the following SQL in your Supabase SQL Editor.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="p-4 bg-slate-950 rounded-md border border-slate-800">
            <pre className="text-xs text-blue-300 overflow-x-auto font-mono max-h-[400px]">
              <code>{MASTER_SQL_SCRIPT}</code>
            </pre>
          </div>
          <div className="flex justify-end gap-2">
            <Button 
                variant="outline" 
                onClick={() => navigator.clipboard.writeText(MASTER_SQL_SCRIPT)}
                className="border-slate-700 text-slate-300 hover:bg-slate-800"
            >
                Copy SQL
            </Button>
            <Button onClick={() => window.open('https://supabase.com/dashboard/project/_/sql', '_blank')} className="bg-green-600 hover:bg-green-500 text-white">
                Open Supabase SQL Editor
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default SupabaseSetup;
